import type { NewEnvironmentType } from './schema';

type SeedEnvironmentType = Required<
  Pick<
    NewEnvironmentType,
    'slug' | 'nameEn' | 'nameAr' | 'color' | 'sortOrder' | 'isDefault' | 'isProtected'
  >
> & {
  descriptionEn: string;
  descriptionAr: string;
};

/** Global environment catalog, ordered by delivery lifecycle. */
export const ENVIRONMENT_TYPES_SEED: readonly SeedEnvironmentType[] = [
  {
    sortOrder: 1,
    slug: 'local',
    nameEn: 'Local',
    nameAr: 'محلي',
    descriptionEn: 'Your own machine during development.',
    descriptionAr: 'جهازك الشخصي أثناء التطوير.',
    color: 'green',
    isDefault: true,
    isProtected: true,
  },
  {
    sortOrder: 2,
    slug: 'dev',
    nameEn: 'Development',
    nameAr: 'التطوير',
    descriptionEn: 'Shared development server, updated continuously.',
    descriptionAr: 'خادم تطوير مشترك يُحدَّث باستمرار.',
    color: 'blue',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 3,
    slug: 'sandbox',
    nameEn: 'Sandbox',
    nameAr: 'بيئة معزولة',
    descriptionEn: 'Isolated space for experiments without touching real data.',
    descriptionAr: 'مساحة معزولة للتجارب دون المساس بالبيانات الحقيقية.',
    color: 'cyan',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 4,
    slug: 'preview',
    nameEn: 'Preview',
    nameAr: 'المعاينة',
    descriptionEn: 'Ephemeral deployment per pull request for reviewing changes.',
    descriptionAr: 'نشر مؤقت لكل طلب دمج لمراجعة التغييرات.',
    color: 'sky',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 5,
    slug: 'test',
    nameEn: 'Testing',
    nameAr: 'الاختبار',
    descriptionEn: 'Automated test runs.',
    descriptionAr: 'تشغيل الاختبارات الآلية.',
    color: 'indigo',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 6,
    slug: 'qa',
    nameEn: 'QA',
    nameAr: 'ضمان الجودة',
    descriptionEn: 'Manual verification by the QA team.',
    descriptionAr: 'تحقق يدوي من فريق ضمان الجودة.',
    color: 'violet',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 7,
    slug: 'sit',
    nameEn: 'Integration',
    nameAr: 'التكامل',
    descriptionEn: 'System integration testing across services.',
    descriptionAr: 'اختبار تكامل الأنظمة والخدمات معاً.',
    color: 'purple',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 8,
    slug: 'pre-stage',
    nameEn: 'Pre-Staging',
    nameAr: 'ما قبل التجهيز',
    descriptionEn: 'Extra verification step before staging.',
    descriptionAr: 'مرحلة تحقق إضافية قبل بيئة التجهيز.',
    color: 'amber',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 9,
    slug: 'staging',
    nameEn: 'Staging',
    nameAr: 'التجهيز',
    descriptionEn: 'Production-like replica for final verification.',
    descriptionAr: 'نسخة مطابقة للإنتاج للتحقق النهائي.',
    color: 'yellow',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 10,
    slug: 'uat',
    nameEn: 'UAT',
    nameAr: 'اختبار قبول المستخدم',
    descriptionEn: 'Client or stakeholder sign-off before release.',
    descriptionAr: 'اعتماد العميل أو أصحاب المصلحة قبل الإطلاق.',
    color: 'lime',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 11,
    slug: 'perf',
    nameEn: 'Performance',
    nameAr: 'الأداء',
    descriptionEn: 'Load and performance testing.',
    descriptionAr: 'اختبارات الحمل والأداء.',
    color: 'teal',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 12,
    slug: 'demo',
    nameEn: 'Demo',
    nameAr: 'العرض التوضيحي',
    descriptionEn: 'Stable environment for client and sales demos.',
    descriptionAr: 'بيئة مستقرة لعروض العملاء والمبيعات.',
    color: 'pink',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 13,
    slug: 'training',
    nameEn: 'Training',
    nameAr: 'التدريب',
    descriptionEn: 'User training with sample data.',
    descriptionAr: 'تدريب المستخدمين ببيانات تجريبية.',
    color: 'slate',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 14,
    slug: 'pre-prod',
    nameEn: 'Pre-Production',
    nameAr: 'ما قبل الإنتاج',
    descriptionEn: 'Last stop before production, with identical configuration.',
    descriptionAr: 'المحطة الأخيرة قبل الإنتاج بإعدادات مطابقة.',
    color: 'orange',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 15,
    slug: 'canary',
    nameEn: 'Canary',
    nameAr: 'الإطلاق التدريجي',
    descriptionEn: 'Gradual rollout to a small share of users.',
    descriptionAr: 'إطلاق تدريجي لنسبة صغيرة من المستخدمين.',
    color: 'rose',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 16,
    slug: 'production',
    nameEn: 'Production',
    nameAr: 'الإنتاج',
    descriptionEn: 'Live environment serving real users.',
    descriptionAr: 'البيئة الحية التي يستخدمها العملاء.',
    color: 'red',
    isDefault: true,
    isProtected: true,
  },
  {
    sortOrder: 17,
    slug: 'hotfix',
    nameEn: 'Hotfix',
    nameAr: 'الإصلاح العاجل',
    descriptionEn: 'Emergency fixes fast-tracked to production.',
    descriptionAr: 'إصلاحات طارئة تُسرَّع إلى الإنتاج.',
    color: 'fuchsia',
    isDefault: false,
    isProtected: false,
  },
  {
    sortOrder: 18,
    slug: 'dr',
    nameEn: 'Disaster Recovery',
    nameAr: 'التعافي من الكوارث',
    descriptionEn: 'Standby site that takes over if production fails.',
    descriptionAr: 'موقع احتياطي يتولى العمل عند تعطل الإنتاج.',
    color: 'stone',
    isDefault: false,
    isProtected: false,
  },
];
